site_name: Erwan Lecarpentier
site_url: https://erwanlecarpentier.github.io/
nav:
    - Home: index.md
    - Publications: publications.md
    - Projects: projects.md
theme:
    name: material # material bootstrap4 mkdocs cinder
    custom_dir: overrides
    favicon: img/favicon.png
    palette:
        primary: deep orange
        accent: orange
        scheme: slate
markdown_extensions:
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/erwanlecarpentier
          name: See my Github page
        - icon: fontawesome/solid/graduation-cap
          link: https://scholar.google.fr/citations?user=jFtlb0oAAAAJ&hl=fr
          name: See my Google Scholar page
        - icon: fontawesome/solid/book
          link: /pdf/erwanlecarpentier-cv.pdf
          name: See my CV
plugins: []
